is_border_leaf: true
lacp_pcs:
  - 14
  - 15
  - 16
  - 17
mclag_member_pcs:
  - lag: PortChannel14
  - lag: PortChannel15
  - lag: PortChannel16
  - lag: PortChannel17
sonic_bgp:
  - bestpath:
      as_path:
        multipath_relax: true
    bgp_as: '{{ bgp_asn }}'
    router_id: '{{ bgp_router_id }}'
  - bgp_as: '{{bgp_asn}}'
    vrf_name: Vrf1
  - bgp_as: '{{ bgp_asn }}'
sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 2
          redistribute:
            - protocol: connected
          safi: unicast
        - advertise_all_vni: true
          afi: l2vpn
          safi: evpn
    bgp_as: '{{bgp_asn}}'
  - address_family:
      afis:
        - advertise_prefix:
            - afi: ipv4
              safi: unicast
          afi: l2vpn
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: Vrf1
sonic_bgp_neighbors:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: Eth1/54
        peer_group: spine-leaf
      - neighbor: Eth1/53
        peer_group: spine-leaf
    peer_group:
      - '{{sonic_bgp_spineleaf_peergroup}}'
sonic_bgp_neighbors_af:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/54
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/53
sonic_config:
  lines: []
sonic_interfaces:
  - description: '"Uplink"'
    enabled: true
    name: Eth1/1
  - description: '"Uplink"'
    enabled: true
    name: Eth1/2
  - description: '"Node-05_eth1-PCIe-NIC1-25G-2"'
    enabled: true
    name: Eth1/9
  - description: '"Node-06_eth1-PCIe-NIC1-25G-2"'
    enabled: true
    name: Eth1/10
  - description: '"Node-07_eth1-PCIe-NIC1-25G-2"'
    enabled: true
    name: Eth1/11
  - description: '"Node-08_eth1-PCIe-NIC1-25G-2"'
    enabled: true
    name: Eth1/12
  - description: '"Uplink to leif-SPINE-2 Eth1/2"'
    enabled: true
    name: Eth1/53
  - description: '"Uplink to leif-SPINE-1 Eth1/2"'
    enabled: true
    name: Eth1/54
  - description: '"MCLAG to leif-LEAF-1 Eth1/55"'
    enabled: true
    name: Eth1/55
  - description: '"MCLAG to leif-LEAF-1 Eth1/56"'
    enabled: true
    name: Eth1/56
  - description: router-id
    name: '{{ loopback_inf0 }}'
  - description: vtep
    name: '{{ loopback_inf1 }}'
  - description: '"LAG to Compute_1_Node-05_bond0"'
    mtu: 9216
    name: PortChannel14
  - description: '"LAG to Compute_1_Node-06_bond0"'
    mtu: 9216
    name: PortChannel15
  - description: '"LAG to Compute_1_Node-07_bond0"'
    mtu: 9216
    name: PortChannel16
  - description: '"LAG to Compute_1_Node-08_bond0"'
    mtu: 9216
    name: PortChannel17
sonic_l2_interfaces:
  - name: Eth1/1
    trunk:
      allowed_vlans:
        - vlan: 200
  - name: Eth1/2
    trunk:
      allowed_vlans:
        - vlan: 200
  - name: PortChannel 14
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 103
  - name: PortChannel 15
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 103
  - name: PortChannel 16
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 103
  - name: PortChannel 17
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 103
  - name: PortChannel100
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 103
        - vlan: 60
sonic_l3_interfaces:
  - ipv6:
      enabled: true
    name: Eth1/53
  - ipv6:
      enabled: true
    name: Eth1/54
  - ipv4:
      addresses:
        - address: '{{ loopback0_ip }}'
    name: '{{ loopback_inf0 }}'
  - ipv4:
      addresses:
        - address: '{{ loopback1_ip }}'
    name: '{{ loopback_inf1 }}'
sonic_lag_interfaces:
  - members:
      interfaces:
        - member: Eth1/9
    mode: lacp
    name: PortChannel14
  - members:
      interfaces:
        - member: Eth1/10
    mode: lacp
    name: PortChannel15
  - members:
      interfaces:
        - member: Eth1/11
    mode: lacp
    name: PortChannel16
  - members:
      interfaces:
        - member: Eth1/12
    mode: lacp
    name: PortChannel17
  - members:
      interfaces:
        - member: Eth1/55
        - member: Eth1/56
    name: PortChannel100
sonic_system:
  anycast_address:
    ipv4: true
    mac_address: '{{ anycast_mac_address }}'
  hostname: leif-LEAF-2
  interface_naming: standard
sonic_vlans:
  - vlan_id: 200
  - vlan_id: 101
  - vlan_id: 102
  - vlan_id: 103
  - vlan_id: 60
sonic_vrf_interfaces:
  - members:
      interfaces:
        - name: Vlan101
        - name: Vlan60
        - name: Vlan102
        - name: Vlan103
        - name: Vlan200
    name: Vrf1
sonic_vxlans:
  - evpn_nvo: nvo1
    name: vtep1
    source_ip: '{{ loopback1_ip.split(''/'')[0] }}'
    vlan_map:
      - vlan: 101
        vni: 10101
      - vlan: 102
        vni: 10102
      - vlan: 103
        vni: 10103
      - vlan: 60
        vni: 600
    vrf_map:
      - vni: 600
        vrf: Vrf1
vlans:
  - 101
  - 102
  - 103
vrfs:
  - Vrf1
